apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cosmic-explorer
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/devikm-2026/cosmic-explorer.git
    targetRevision: main
    path: k8s

  destination:
    server: https://kubernetes.default.svc
    namespace: default

  syncPolicy:
    automated:
      prune: true
      selfHeal: true