apiVersion: apps/v1
kind: Deployment
metadata:
  name: cosmic-explorer
spec:
  replicas: 3

  selector:
    matchLabels:
      app: cosmic-explorer

  template:
    metadata:
      labels:
        app: cosmic-explorer

    spec:
      imagePullSecrets:
        - name: jfrog-secret

      containers:
        - name: cosmic-explorer
          image: trial7uwzzo.jfrog.io/docker-trial/cosmic-explorer:v1
          imagePullPolicy: Always
          ports:
            - containerPort: 80